### ISSUE TITLE
Call audio problem

### ISSUE THREAD

**Issue by vepsa97** [masterdoctor/LineageOS-p8lite-community#16] opened 2017-01-20 16:36 UTC
If i call someone he hears me but i dont hear him.

**Comment by west2554** [comment] 2017-01-20 16:40
Call speaker does work
but use Hands-Free mode work.

**Comment by masterdoctor** [comment] 2017-01-20 17:27
This is a duplicate of https://github.com/masterdoctor/LineageOS-p8lite-community/issues/7

**Closed by masterdoctor** 2017-01-20 17:27 UTC
