### ISSUE TITLE
RIL

### ISSUE THREAD

**Issue by KernellyPoland** [masterdoctor/LineageOS-p8lite-community#26] opened 2017-01-24 06:35 UTC
In the Polish mobile lose mobile network coverage
<br />
<br />Connectivity issues...

**Comment by xdk78** [comment] 2017-01-24 08:15
Me too, but everyone has similar problem.

**Comment by Bartixxx32** [comment] 2017-01-24 10:28
i dont tested now but i think is normal i set label as Bug

**Comment by XePeleato** [comment] 2017-01-24 10:35
This happens because the Huawei Java RIL layer doesn't have the correct signal thresholds. It will be fixed.

**Comment by Untouch007** [comment] 2017-01-24 13:34
Im guessing we will be waiting on this fix before the next update rolls out

**Comment by kaitek666** [comment] 2017-03-20 16:47
Any chance of fixing this soon? I also noticed that it only wants to connect to LTE, never 3G/2G.

**Comment by masterdoctor** [comment] 2017-03-24 21:02
Hi, @kaitek666 
The other developers are working on it - I have more exams to do before I can get back to it but it seems to me that this is almost fixed.

**Comment by Bartixxx32** [comment] 2017-03-25 10:31
w jakich sieciach? / in what operators?

**Comment by kaitek666** [comment] 2017-04-04 12:10
@Bartixxx32 I can confirm Play and Mobile Vikings.

**Closed** 2018-01-03 20:38 UTC
Labels: bug
