### ISSUE TITLE
ALE-L02 Wifi does not work

### ISSUE THREAD

**Issue by west2554** [masterdoctor/LineageOS-p8lite-community#12] opened 2017-01-20 03:04 UTC
Stuck at "Turning Wi-Fi on" and loss MAC Address

I'm bad english sorry.

**Comment by masterdoctor** [comment] 2017-01-20 07:10
MAC address doesn't show up on my ALE-L21 but WiFi does work.
I'll look into it for your device.

**Comment by Balor21** [comment] 2017-01-20 07:33
same here with a p8 lite ale l23 changed to ale l21 and a model number hi6210sft before install this rom,this hi6210sft can be a problem?

**Comment by masterdoctor** [comment] 2017-01-20 12:01
@Balor21 I have an ALE-L21 and so I've set the model number to L21.
Do you mean that the model number used to be hi6210sft and is now ALE-L21?

The MAC address, always returns this - it's a known bug and I think L02 and L23 have different WiFi chips.

**Comment by ClassyLion** [comment] 2017-01-20 12:13
@masterdoctor He changed model number from ALE L23 to ALE L21. He made the phone think that is L21, so he could use L21 roms and other things.

**Comment by masterdoctor** [comment] 2017-01-20 12:27
@ClassyLion Oh, I see!
My ROM doesn't actually perform a check to see if the ROM is supported by or will work on the phone so for future reference, nobody has to do this to run my ROM if it's supported.

**Comment by masterdoctor** [comment] 2017-01-20 12:28
I suspect that they have different WiFi chips, so if someone could get any information on the WiFi chip in ALE-L02 or ALE-L23, I'd be grateful. (I can't because I have an ALE-L21)

**Comment by west2554** [comment] 2017-01-20 15:06
I check on ADB Shell
WIFI Chipset "**Hi110x**" Right?

**Comment by masterdoctor** [comment] 2017-01-20 16:11
I can confirm that this is an issue with ALE-L23.

@west2554 I'm not sure, I think that might be the controller/driver.
Is this on EMUI (stock) or LineageOS?

**Comment by west2554** [comment] 2017-01-20 16:23
@masterdoctor data form stock EMUI sir.
P.S. I flash only system.img not work (boot logo stuck) if flash custom boot.img is work

**Comment by masterdoctor** [comment] 2017-01-20 17:17
Okay. @west2554  I'll update the install guide to include steps for custom boot.img

**Comment by Balor21** [comment] 2017-01-20 19:19
My Phone Is a Ale l23 model,but i use the change of Ale l23 to Ale l21 vía Flashrom AND install Android 6,after installing b588 ROM got model name hi6210sft AND i install this lineageos Rom with this model,can be a error for this? I Will try again changing the model to Ale l21 before install,AND i got the same chip hi110x,always is a inssue with Ale l23

**Comment by masterdoctor** [comment] 2017-01-20 19:59
Okay, thanks.

**Comment by Balor21** [comment] 2017-01-20 20:20
If you need any info of my device just say hehe

**Comment by masterdoctor** [comment] 2017-01-25 00:09
Has this been fixed with the update?

**Comment by west2554** [comment] 2017-01-25 01:41
@masterdoctor Does not work sir.

**Comment by Bartixxx32** [comment] 2017-01-25 10:33
no libares

**Closed** 2018-01-03 20:38 UTC
Labels: bug
